## Final Project

Using equipments like Jawbone Up, Nike FuelBand, and Fitbit
now it is possible to measure perosnal performances. People
usually measure their performance quantity but not the performance
quality. Main goal of this project is to use data from accelerometers
on the belt, forearm, arm, and dumbell of 6 participants and precict
the manner in which they did the exercise.

This project had a very long data set.
So training took very long time.
I have applied random forest method to classify the model to 
predict the classe variable.

To measure the quality of workout classe is the most suitbale variable.
Now to model the data I have used random forest because with my little 
knowledge about algorithms I think this would be the best algorithm to 
classify people based on their behaviours.

code 

```{r code}
library(caret)
library(randomForest)

training <- read.csv("pml-training.csv")
testing <- read.csv("pml-testing.csv")


modfit <- train((classe ~ raw_timestamp_part_1 + raw_timestamp_part_2+
                  + roll_belt + pitch_belt + yaw_belt
                + total_accel_belt + magnet_belt_y +
                  magnet_belt_z + roll_arm + pitch_arm+
                  + yaw_arm + total_accel_arm + magnet_arm_x +
                  magnet_arm_y + magnet_arm_z + roll_dumbbell
                + pitch_dumbbell+ yaw_dumbbell + accel_dumbbell_z
                + magnet_dumbbell_x + magnet_dumbbell_y +
                  magnet_dumbbell_z + roll_forearm+ pitch_forearm+
                  yaw_forearm+ gyros_forearm_z + accel_forearm_x +
                  accel_forearm_y + accel_forearm_z +
                  magnet_forearm_x + magnet_forearm_z) , data=training, method="rf")

pred <- predict(modfit, testing)
pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}

pml_write_files(pred) 

varimportance <- varImp(modfit, scale=FALSE)

plot(varimportance)

plot(pred, col=rainbow(10))


```